name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - uses: "actions/checkout@v2"
      - name: "Install Rust"
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          
        run: |
          cargo build --release
          echo "done build linux!"
          
          cargo build --release --target=x86_64-pc-windows-gnu
          echo "done build windows!"

      - uses: "marvinpinto/action-automatic-releases@latest"
      - name: "Upload release"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
            target/release/perling_vm
